import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				<h1 className=' font-bold text-6xl'>Hello Next.js</h1>
			</div>
		</>
	)
}
