import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

export default function Home() {
	const { data: session } = useSession()
	const router = useRouter()
	// const { session, loadingSession } = useSession()

	// if (loadingSession) {
	// 	return <p>Loading...</p>
	// }
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{!session && (
				<>
					<button onClick={() => signIn()}>Sign in</button>
				</>
			)}

			{session && (
				<>
					<button onClick={() => signOut()}>Sign out</button>
					{router.push('/customer')}
				</>
			)}
		</>
	)
}
